FROM python:3.11-slim
WORKDIR /app
COPY services/ /app/services
COPY ai/ /app/ai
COPY requirements.txt /app
RUN pip install -r requirements.txt
CMD ["python", "/app/services/correlator/correlator.py"]
